/* Detail views have real, optional fields. Empty sections never become fake case studies. */
(() => {
  const {esc, icon, image, position, videoInfo, safeURL, tags} = window.P;
  const paragraphs = text => String(text || '').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('');
  window.PORTFOLIO_VIEWS.projectDetail = (p, projects) => {
    const media=videoInfo(p.video), external=safeURL(p.link);
    const index=projects.findIndex(item=>item.id===p.id);
    const next=projects[(index+1)%projects.length];
    const cs=p.caseStudy || {}, compare=p.compare || {};
    const sections=[['The brief',cs.brief],['My role',cs.role],['The approach',cs.process],['The outcome',cs.outcome]].filter(([,v])=>v);
    return `<div class="modal-header"><p class="eyebrow">${icon('film')} ${esc(p.category)} / ${p.preview?'CONCEPT PREVIEW':'PROJECT DETAILS'}</p><div class="modal-header-actions"><button class="icon-button" data-action="share" type="button" aria-label="Copy project link">${icon('copy')}</button><button class="icon-button" type="button" data-action="close-project" aria-label="Close project">${icon('close')}</button></div></div>
      <div id="media-stage" class="media-stage ${media?'has-video':''} ${p.aspect==='9/16'?'portrait':''} ${p.aspect==='1/1'?'square':''}"><img src="${esc(image(p.cover))}" alt="${esc(p.title)} artwork" style="object-position:${esc(position(p.coverPosition))}" width="960" height="540">${media?`<button class="media-play" type="button" data-action="play-video">${icon('play')} Play film</button>`:`<span class="media-preview-note">${p.preview?'ARTWORK CONCEPT / NO VIDEO ADDED':'PROJECT ARTWORK'}</span>`}</div>
      <div class="modal-body"><div><h2 id="project-title">${esc(p.title)}</h2><p class="modal-subtitle">${esc(p.subtitle)}</p><div class="modal-description">${paragraphs(p.description)}</div>${p.preview?'<p class="preview-disclaimer">Concept artwork retained from the original portfolio. This is not a published case study; finished media and verified production details have not been added.</p>':''}${p.video&&!media?'<p class="preview-disclaimer">Unsupported media link. Use a direct MP4/WebM file, YouTube or Vimeo URL.</p>':''}</div><aside class="modal-meta"><h3>CREATIVE FOCUS</h3><div class="modal-tags">${tags(p.tags)}</div>${p.tools?.length?`<h3>THE TOOLKIT</h3><p>${p.tools.map(esc).join(' &middot; ')}</p>`:''}${external?`<h3>MORE TO EXPLORE</h3><a class="text-link" href="${esc(external)}" target="_blank" rel="noopener noreferrer">View full project ${icon('arrow-up')}</a>`:''}</aside></div>
      ${sections.length?`<section class="case-study" aria-label="Behind the project"><p class="eyebrow">${p.preview?'CONCEPT DIRECTION':'BEHIND THE FRAMES'}</p><div class="case-grid">${sections.map(([title,value],i)=>`<div><span class="case-index">0${i+1}</span><h3>${title}</h3>${paragraphs(value)}</div>`).join('')}</div></section>`:''}
      ${compare.before&&compare.after?`<section class="comparison-section" aria-labelledby="compare-heading"><div class="section-mini-heading"><h3 id="compare-heading">The difference is in the details.</h3><span>DRAG TO COMPARE</span></div><div class="image-comparison" style="--split:50%"><img src="${esc(image(compare.after))}" alt="${esc(compare.afterLabel)}" width="960" height="540"><img class="comparison-before" src="${esc(image(compare.before))}" alt="${esc(compare.beforeLabel)}" width="960" height="540"><span class="compare-label before">${esc(compare.beforeLabel)}</span><span class="compare-label after">${esc(compare.afterLabel)}</span><span class="comparison-line" aria-hidden="true"></span></div><label class="compare-slider-label" for="compare-slider">Reveal ${esc(compare.beforeLabel)} <output id="compare-value">50%</output></label><input id="compare-slider" type="range" min="0" max="100" value="50" aria-label="Before and after comparison"></section>`:''}
      <div class="modal-footer"><button class="text-button" type="button" data-action="close-project">Back to exploring</button>${next&&projects.length>1&&index>=0?`<a class="text-link" href="#projects/${encodeURIComponent(next.id)}">Next: ${esc(next.title)} ${icon('arrow')}</a>`:`<a class="text-link" href="#contact">Let's create something ${icon('arrow-up')}</a>`}</div>`;
  };
  window.PORTFOLIO_VIEWS.tipDetail = (t, saved, tips) => {
    const source=safeURL(t.sourceURL), download=safeURL(t.downloadURL,true), media=videoInfo(t.video);
    const related=tips.find(item=>item.id!==t.id && item.topic===t.topic && item.published!==false) || tips.find(item=>item.id!==t.id && item.published!==false);
    const minutes=Math.max(1, Math.ceil(`${t.body} ${(t.steps||[]).join(' ')}`.split(/\s+/).length/180));
    return `<div class="modal-header"><a class="text-link" href="#lab">${icon('lab')} THE LAB</a><div class="modal-header-actions"><button class="icon-button save-note" type="button" data-save-note="${esc(t.id)}" aria-pressed="${saved.includes(t.id)}" aria-label="${saved.includes(t.id)?'Unsave':'Save'} note">${icon('bookmark')}</button><button class="icon-button" type="button" data-action="share" aria-label="Copy note link">${icon('copy')}</button><button class="icon-button" type="button" data-action="close-tip" aria-label="Close note">${icon('close')}</button></div></div>
      <article class="tip-article"><header class="tip-heading"><p class="eyebrow">${esc(t.topic)} / ${esc(t.kind)}</p><h2 id="tip-title">${esc(t.title)}</h2><p>${esc(t.summary)}</p><div class="tip-reading-meta"><span>${icon('clock')} ${minutes} min read</span>${t.version?`<span>${esc(t.version)}</span>`:''}</div></header><div class="reader-grid"><div class="reader-body">${paragraphs(t.body)}${t.steps?.length?`<h3>Try this</h3><ol class="tip-steps">${t.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>`:''}${t.code?`<div class="code-block"><div><span>SNIPPET</span><button type="button" class="text-button" data-action="copy-tip-code">Copy ${icon('copy')}</button></div><pre tabindex="0"><code>${esc(t.code)}</code></pre></div>`:''}${media?`<a class="button button-quiet" href="${esc(safeURL(t.video,true))}" target="_blank" rel="noopener noreferrer">Watch the original demo ${icon('arrow-up')}</a>`:''}</div><aside class="reader-aside"><div class="reader-visual art-${esc(t.visual)}" aria-hidden="true">${window.PORTFOLIO_VIEWS.labArt(t.visual)}</div><p class="eyebrow">KEEP EXPLORING</p>${source?`<a class="reference-link" href="${esc(source)}" target="_blank" rel="noopener noreferrer">${esc(t.sourceTitle || 'Original reference')} ${icon('arrow-up')}</a>`:'<p>Add your original reference in Content Studio.</p>'}${download?`<a class="reference-link" href="${esc(download)}" target="_blank" rel="noopener noreferrer">Project file / resource ${icon('download')}</a>`:''}${t.sample?'<p class="starter-note">Starter editorial example with reference documentation. Replace or adapt it with your own tested recipe before presenting it as personal experience.</p>':''}</aside></div></article>
      <div class="modal-footer"><button type="button" class="text-button" data-action="close-tip">Back to the notebook</button>${related?`<a class="text-link" href="#lab/${encodeURIComponent(related.id)}">Another useful note ${icon('arrow')}</a>`:''}</div>`;
  };
})();
