/* Every visual here is lightweight, native UI. Nothing autoplays. */
window.PORTFOLIO_VIEWS.labArt = (type) => {
  const {icon} = window.P;
  if (type === 'curves') return '<svg viewBox="0 0 240 110" fill="none" aria-hidden="true"><path d="M25 90H218M25 90V14" stroke="currentColor" opacity=".15"/><path d="M27 88 213 19" stroke="currentColor" stroke-dasharray="4 5" opacity=".25"/><path d="M27 88C97 88 67 18 213 18" stroke="currentColor" stroke-width="3"/><circle cx="27" cy="88" r="5" fill="currentColor"/><circle cx="213" cy="18" r="5" fill="currentColor"/></svg>';
  if (type === 'loop') return '<span class="loop-glyph" aria-hidden="true">&infin;</span><span class="art-caption">loopOut("cycle", 0)</span>';
  if (type === 'glow') return '<span class="glow-orb" aria-hidden="true"></span><span class="art-caption">less noise. more feeling.</span>';
  if (type === 'render') return '<span class="render-cubes" aria-hidden="true"><i></i><i></i><i></i></span><span class="art-caption">SAMPLES &ne; EVERYTHING</span>';
  if (type === 'plugins') return `<span class="plugin-stack" aria-hidden="true"><i>${icon('plus')}</i><i>${icon('lab')}</i><i>${icon('check')}</i></span>`;
  return '<span class="workflow-files" aria-hidden="true"><i>01 / SOURCE</i><i>02 / COMPS</i><i>03 / DELIVERY <b>&check;</b></i></span>';
};
window.PORTFOLIO_VIEWS.labCards = (tips, topic = 'All Notes', query = '', saved = [], onlySaved = false) => {
  const {esc, icon} = window.P;
  const raw=query.trim().toLowerCase();
  const needle=raw==='ae'?'after effects':raw;
  const filtered = tips.filter(t => t.published !== false && (topic==='All Notes' || t.topic===topic) && (!onlySaved || saved.includes(t.id)) && `${t.title} ${t.topic} ${t.summary} ${t.kind}`.toLowerCase().includes(needle));
  if (!filtered.length) return `<div class="empty-state"><span class="empty-symbol">${icon('book')}</span><h2>${onlySaved ? 'Keep a little inspiration.' : 'No notes found.'}</h2><p>${onlySaved ? 'Bookmark a note to keep it in this browser.' : 'Try a different topic or search phrase.'}</p><button class="text-button" type="button" data-action="reset-lab">Explore all notes ${icon('arrow')}</button></div>`;
  return filtered.map((t,i) => `<article class="note-card"><a class="note-art art-${esc(t.visual)}" href="#lab/${encodeURIComponent(t.id)}" aria-label="Read ${esc(t.title)}">${window.PORTFOLIO_VIEWS.labArt(t.visual)}<span class="note-number">${String(i+1).padStart(2,'0')}</span></a><div class="note-copy"><div class="note-meta"><span>${esc(t.topic)}</span><span>${esc(t.kind)}</span></div><h3><a href="#lab/${encodeURIComponent(t.id)}">${esc(t.title)}</a></h3><p>${esc(t.summary)}</p><div class="note-bottom"><a class="text-link" href="#lab/${encodeURIComponent(t.id)}">Read note ${icon('arrow-up')}</a><button type="button" class="save-note" data-save-note="${esc(t.id)}" aria-pressed="${saved.includes(t.id)}" aria-label="${saved.includes(t.id)?'Unsave':'Save'} ${esc(t.title)}">${icon('bookmark')}</button></div></div></article>`).join('');
};
window.PORTFOLIO_VIEWS.lab = (site, projects, tips) => {
  const {esc, icon} = window.P;
  const topics = ['All Notes','After Effects','Blender','Workflow','Plugins'];
  const cfg = site.lab;
  return `<div class="page-heading lab-heading reveal"><div><p class="eyebrow"><span class="tiny-line"></span> THE LAB / TIPS &amp; TRICKS</p><h1 tabindex="-1">${esc(cfg.title)}<br><em>${esc(cfg.accent)}</em></h1><p>${esc(cfg.intro)}</p></div><div class="lab-stamp" aria-hidden="true">${icon('lab')}<span>PLAY. LEARN.<br>MAKE. REPEAT.</span></div></div>
    ${cfg.showPlayground ? `<section class="motion-playground reveal" aria-labelledby="playground-title"><div class="playground-copy"><p class="eyebrow"><span class="status-dot"></span> INTERACTIVE EXPERIMENT / 001</p><h2 id="playground-title">Don't just see it.<br><em>Feel the difference.</em></h2><p>Same distance. Same duration.<br>A different curve changes everything.</p><div class="curve-options" role="group" aria-label="Motion curve"><button type="button" data-curve="smooth" aria-pressed="true">Smooth</button><button type="button" data-curve="snappy" aria-pressed="false">Snappy</button><button type="button" data-curve="bounce" aria-pressed="false">Bounce</button></div><label class="duration-label" for="motion-duration">Duration <output id="duration-value" for="motion-duration">1.2s</output></label><input id="motion-duration" class="duration-range" type="range" min="400" max="2200" step="100" value="1200"><button type="button" class="button button-primary play-motion" data-action="play-motion">${icon('play')} Play the difference</button><p class="playground-note" id="playground-message">Browser demo. No plugins. No autoplay.</p></div><div class="motion-stage"><div class="stage-heading"><span>MOTION STUDY</span><span id="curve-name">SMOOTH / EASE OUT</span></div><div class="motion-lanes"><div class="motion-lane"><span class="lane-label">LINEAR <small>constant speed</small></span><div class="motion-rail"><div class="motion-token token-linear" aria-hidden="true">${icon('star')}</div><span class="finish-point" aria-hidden="true"></span></div></div><div class="motion-lane"><span class="lane-label">YOUR CURVE <small id="lane-caption">a softer landing</small></span><div class="motion-rail"><div class="motion-token token-curve" aria-hidden="true">${icon('star')}</div><span class="finish-point" aria-hidden="true"></span></div></div></div><div class="stage-bottom"><span class="bezier-thumb">${window.PORTFOLIO_VIEWS.labArt('curves')}</span><div><span>THE LITTLE DETAILS MATTER</span><code id="curve-code">cubic-bezier(.22, 1, .36, 1)</code><button class="text-button" type="button" data-action="copy-curve">Copy CSS curve ${icon('copy')}</button></div></div><button type="button" class="button button-primary stage-play" data-action="play-motion">${icon('play')} Play the difference</button></div></section>` : ''}
    <section class="lab-notes" aria-labelledby="notes-heading"><div class="notes-heading"><div><p class="eyebrow">THE OPEN NOTEBOOK</p><h2 id="notes-heading">Small notes. <em>Useful ideas.</em></h2></div><label class="inline-search"><span class="sr-only">Search tips</span>${icon('search')}<input id="lab-search" type="search" placeholder="Search a tip or tool" maxlength="100" autocomplete="off"></label></div><div class="lab-toolbar"><div class="filters" role="group" aria-label="Filter notes">${topics.map((t,i)=>`<button type="button" class="filter ${i?'':'is-active'}" data-topic="${esc(t)}" aria-pressed="${!i}">${esc(t)}</button>`).join('')}</div><button type="button" class="saved-filter" data-action="saved-notes" aria-pressed="false">${icon('bookmark')} Saved <span id="saved-count">0</span></button></div><div id="lab-grid" class="lab-grid">${window.PORTFOLIO_VIEWS.labCards(tips)}</div><p id="lab-announcement" class="sr-only" role="status" aria-live="polite"></p><p class="lab-editorial-note">Starter notes with official references. Personal experiments and tested recipes can be added in Content Studio.</p></section>`;
};
